//
//  FilterType.swift
//  WesWorld FX
//
//  Filter definitions matching the original web app
//

import Foundation

enum FilterType: String, CaseIterable {
    case none = "None (Original)"
    
    // Favorites
    case bulgeEyes = "Bulge Eyes"
    case funhouseMirror = "Funhouse Mirror"
    case funnySquash = "Funny Squash"
    case pinchCheeks = "Pinch Cheeks"
    case pincushion = "Pincushion"
    case radialWobble = "Radial Wobble"
    case ultimateDistortion = "Ultimate Distortion"
    case waterRipple = "Water Ripple"
    case wobbleFace = "Wobble Face"
    
    // Distortion
    case complexRipple = "Complex Ripple"
    case complexRippleV1 = "Complex Ripple V1"
    case elasticFace = "Elastic Face"
    case elasticStretch = "Elastic Stretch"
    case elasticStretchV1 = "Elastic Stretch V1"
    case funnyStretch = "Funny Stretch"
    case funnyStretchV1 = "Funny Stretch V1"
    case gentleRipple = "Gentle Ripple"
    case lensDistortion = "Lens Distortion"
    case lensDistortionV1 = "Lens Distortion V1"
    case multiRipple = "Multi Ripple"
    case multiRippleV1 = "Multi Ripple V1"
    case radialSqueeze = "Radial Squeeze"
    case radialSqueezeV1 = "Radial Squeeze V1"
    case smushFace = "Smush Face"
    case squeezeHorizontal = "Squeeze Horizontal"
    case squeezeHorizontalV1 = "Squeeze Horizontal V1"
    case squeezeVertical = "Squeeze Vertical"
    case squeezeVerticalV1 = "Squeeze Vertical V1"
    case squishFace = "Squish Face"
    case squishFaceV1 = "Squish Face V1"
    case stretchFace = "Stretch Face"
    case stretchFaceV1 = "Stretch Face V1"
    case upsideDown = "Upside Down"
    case upsideDownV1 = "Upside Down V1"
    case warpFace = "Warp Face"
    case warpFaceV1 = "Warp Face V1"
    case waveDistortion = "Wave Distortion"
    case waveDistortionV1 = "Wave Distortion V1"
    
    // Elastic Distortions
    case elasticWarp1 = "Elastic Warp 1"
    case elasticWarp2 = "Elastic Warp 2"
    case elasticWarp3 = "Elastic Warp 3"
    case elasticWarp4 = "Elastic Warp 4"
    case elasticWarp5 = "Elastic Warp 5"
    case elasticWarp6 = "Elastic Warp 6"
    case elasticWarp7 = "Elastic Warp 7"
    case elasticWarp8 = "Elastic Warp 8"
    case elasticWarp9 = "Elastic Warp 9"
    case elasticWarp10 = "Elastic Warp 10"
    case elasticWarp11 = "Elastic Warp 11"
    case elasticWarp12 = "Elastic Warp 12"
    case elasticWarp13 = "Elastic Warp 13"
    case elasticWarp14 = "Elastic Warp 14"
    
    // Stretch Distortions
    case stretchDistort1 = "Stretch Distort 1"
    case stretchDistort2 = "Stretch Distort 2"
    case stretchDistort3 = "Stretch Distort 3"
    case stretchDistort4 = "Stretch Distort 4"
    case stretchDistort5 = "Stretch Distort 5"
    case stretchDistort6 = "Stretch Distort 6"
    case stretchDistort7 = "Stretch Distort 7"
    case stretchDistort8 = "Stretch Distort 8"
    case stretchDistort9 = "Stretch Distort 9"
    case stretchDistort10 = "Stretch Distort 10"
    case stretchDistort11 = "Stretch Distort 11"
    case stretchDistort12 = "Stretch Distort 12"
    case stretchDistort13 = "Stretch Distort 13"
    case stretchDistort14 = "Stretch Distort 14"
    
    // Bulge Distortions
    case bulgeFunhouse1 = "Bulge Funhouse 1"
    case bulgeFunhouse2 = "Bulge Funhouse 2"
    case bulgeFunhouse3 = "Bulge Funhouse 3"
    case bulgeFunhouse4 = "Bulge Funhouse 4"
    case bulgeFunhouse5 = "Bulge Funhouse 5"
    case bulgeFunhouse6 = "Bulge Funhouse 6"
    case bulgeFunhouse7 = "Bulge Funhouse 7"
    case bulgeFunhouse8 = "Bulge Funhouse 8"
    case bulgeFunhouse9 = "Bulge Funhouse 9"
    case bulgeFunhouse10 = "Bulge Funhouse 10"
    case bulgeFunhouse11 = "Bulge Funhouse 11"
    case bulgeFunhouse12 = "Bulge Funhouse 12"
    case bulgeFunhouse13 = "Bulge Funhouse 13"
    case bulgeFunhouse14 = "Bulge Funhouse 14"
    
    // Favorite Filter Variations
    case bulgeEyesV2 = "Bulge Eyes V2"
    case bulgeEyesV3 = "Bulge Eyes V3"
    case bulgeEyesV4 = "Bulge Eyes V4"
    case bulgeEyesV5 = "Bulge Eyes V5"
    
    case funhouseMirrorV2 = "Funhouse Mirror V2"
    case funhouseMirrorV3 = "Funhouse Mirror V3"
    case funhouseMirrorV4 = "Funhouse Mirror V4"
    case funhouseMirrorV5 = "Funhouse Mirror V5"
    
    case funnySquashV2 = "Funny Squash V2"
    case funnySquashV3 = "Funny Squash V3"
    case funnySquashV4 = "Funny Squash V4"
    case funnySquashV5 = "Funny Squash V5"
    
    case pinchCheeksV2 = "Pinch Cheeks V2"
    case pinchCheeksV3 = "Pinch Cheeks V3"
    case pinchCheeksV4 = "Pinch Cheeks V4"
    case pinchCheeksV5 = "Pinch Cheeks V5"
    
    case pincushionV2 = "Pincushion V2"
    case pincushionV3 = "Pincushion V3"
    case pincushionV4 = "Pincushion V4"
    case pincushionV5 = "Pincushion V5"
    
    case radialWobbleV2 = "Radial Wobble V2"
    case radialWobbleV3 = "Radial Wobble V3"
    case radialWobbleV4 = "Radial Wobble V4"
    case radialWobbleV5 = "Radial Wobble V5"
    
    case ultimateDistortionV2 = "Ultimate Distortion V2"
    case ultimateDistortionV3 = "Ultimate Distortion V3"
    case ultimateDistortionV4 = "Ultimate Distortion V4"
    case ultimateDistortionV5 = "Ultimate Distortion V5"
    
    case waterRippleV2 = "Water Ripple V2"
    case waterRippleV3 = "Water Ripple V3"
    case waterRippleV4 = "Water Ripple V4"
    case waterRippleV5 = "Water Ripple V5"
    
    case wobbleFaceV2 = "Wobble Face V2"
    case wobbleFaceV3 = "Wobble Face V3"
    case wobbleFaceV4 = "Wobble Face V4"
    case wobbleFaceV5 = "Wobble Face V5"
    
    var displayName: String {
        return rawValue
    }
    
    var filterId: Int {
        return FilterType.allCases.firstIndex(of: self) ?? 0
    }
    
    var metalFunctionName: String {
        switch self {
        case .none: return ""
        case .bulgeEyes: return "bulge_eyes"
        case .funhouseMirror: return "funhouse_mirror"
        case .funnySquash: return "funny_squash"
        case .pinchCheeks: return "pinch_cheeks"
        case .pincushion: return "pincushion"
        case .radialWobble: return "radial_wobble"
        case .ultimateDistortion: return "ultimate_distortion"
        case .waterRipple: return "water_ripple"
        case .wobbleFace: return "wobble_face"
        case .complexRipple: return "complex_ripple"
        case .complexRippleV1: return "complex_ripple_v1"
        case .elasticFace: return "elastic_face"
        case .elasticStretch: return "elastic_stretch"
        case .elasticStretchV1: return "elastic_stretch_v1"
        case .funnyStretch: return "funny_stretch"
        case .funnyStretchV1: return "funny_stretch_v1"
        case .gentleRipple: return "gentle_ripple"
        case .lensDistortion: return "lens_distortion"
        case .lensDistortionV1: return "lens_distortion_v1"
        case .multiRipple: return "multi_ripple"
        case .multiRippleV1: return "multi_ripple_v1"
        case .radialSqueeze: return "radial_squeeze"
        case .radialSqueezeV1: return "radial_squeeze_v1"
        case .smushFace: return "smush_face"
        case .squeezeHorizontal: return "squeeze_horizontal"
        case .squeezeHorizontalV1: return "squeeze_horizontal_v1"
        case .squeezeVertical: return "squeeze_vertical"
        case .squeezeVerticalV1: return "squeeze_vertical_v1"
        case .squishFace: return "squish_face"
        case .squishFaceV1: return "squish_face_v1"
        case .stretchFace: return "stretch_face"
        case .stretchFaceV1: return "stretch_face_v1"
        case .upsideDown: return "upside_down"
        case .upsideDownV1: return "upside_down_v1"
        case .warpFace: return "warp_face"
        case .warpFaceV1: return "warp_face_v1"
        case .waveDistortion: return "wave_distortion"
        case .waveDistortionV1: return "wave_distortion_v1"
        case .elasticWarp1: return "elastic_warp_1"
        case .elasticWarp2: return "elastic_warp_2"
        case .elasticWarp3: return "elastic_warp_3"
        case .elasticWarp4: return "elastic_warp_4"
        case .elasticWarp5: return "elastic_warp_5"
        case .elasticWarp6: return "elastic_warp_6"
        case .elasticWarp7: return "elastic_warp_7"
        case .elasticWarp8: return "elastic_warp_8"
        case .elasticWarp9: return "elastic_warp_9"
        case .elasticWarp10: return "elastic_warp_10"
        case .elasticWarp11: return "elastic_warp_11"
        case .elasticWarp12: return "elastic_warp_12"
        case .elasticWarp13: return "elastic_warp_13"
        case .elasticWarp14: return "elastic_warp_14"
        case .stretchDistort1: return "stretch_distort_1"
        case .stretchDistort2: return "stretch_distort_2"
        case .stretchDistort3: return "stretch_distort_3"
        case .stretchDistort4: return "stretch_distort_4"
        case .stretchDistort5: return "stretch_distort_5"
        case .stretchDistort6: return "stretch_distort_6"
        case .stretchDistort7: return "stretch_distort_7"
        case .stretchDistort8: return "stretch_distort_8"
        case .stretchDistort9: return "stretch_distort_9"
        case .stretchDistort10: return "stretch_distort_10"
        case .stretchDistort11: return "stretch_distort_11"
        case .stretchDistort12: return "stretch_distort_12"
        case .stretchDistort13: return "stretch_distort_13"
        case .stretchDistort14: return "stretch_distort_14"
        case .bulgeFunhouse1: return "bulge_funhouse_1"
        case .bulgeFunhouse2: return "bulge_funhouse_2"
        case .bulgeFunhouse3: return "bulge_funhouse_3"
        case .bulgeFunhouse4: return "bulge_funhouse_4"
        case .bulgeFunhouse5: return "bulge_funhouse_5"
        case .bulgeFunhouse6: return "bulge_funhouse_6"
        case .bulgeFunhouse7: return "bulge_funhouse_7"
        case .bulgeFunhouse8: return "bulge_funhouse_8"
        case .bulgeFunhouse9: return "bulge_funhouse_9"
        case .bulgeFunhouse10: return "bulge_funhouse_10"
        case .bulgeFunhouse11: return "bulge_funhouse_11"
        case .bulgeFunhouse12: return "bulge_funhouse_12"
        case .bulgeFunhouse13: return "bulge_funhouse_13"
        case .bulgeFunhouse14: return "bulge_funhouse_14"
        case .bulgeEyesV2: return "bulge_eyes_v2"
        case .bulgeEyesV3: return "bulge_eyes_v3"
        case .bulgeEyesV4: return "bulge_eyes_v4"
        case .bulgeEyesV5: return "bulge_eyes_v5"
        case .funhouseMirrorV2: return "funhouse_mirror_v2"
        case .funhouseMirrorV3: return "funhouse_mirror_v3"
        case .funhouseMirrorV4: return "funhouse_mirror_v4"
        case .funhouseMirrorV5: return "funhouse_mirror_v5"
        case .funnySquashV2: return "funny_squash_v2"
        case .funnySquashV3: return "funny_squash_v3"
        case .funnySquashV4: return "funny_squash_v4"
        case .funnySquashV5: return "funny_squash_v5"
        case .pinchCheeksV2: return "pinch_cheeks_v2"
        case .pinchCheeksV3: return "pinch_cheeks_v3"
        case .pinchCheeksV4: return "pinch_cheeks_v4"
        case .pinchCheeksV5: return "pinch_cheeks_v5"
        case .pincushionV2: return "pincushion_v2"
        case .pincushionV3: return "pincushion_v3"
        case .pincushionV4: return "pincushion_v4"
        case .pincushionV5: return "pincushion_v5"
        case .radialWobbleV2: return "radial_wobble_v2"
        case .radialWobbleV3: return "radial_wobble_v3"
        case .radialWobbleV4: return "radial_wobble_v4"
        case .radialWobbleV5: return "radial_wobble_v5"
        case .ultimateDistortionV2: return "ultimate_distortion_v2"
        case .ultimateDistortionV3: return "ultimate_distortion_v3"
        case .ultimateDistortionV4: return "ultimate_distortion_v4"
        case .ultimateDistortionV5: return "ultimate_distortion_v5"
        case .waterRippleV2: return "water_ripple_v2"
        case .waterRippleV3: return "water_ripple_v3"
        case .waterRippleV4: return "water_ripple_v4"
        case .waterRippleV5: return "water_ripple_v5"
        case .wobbleFaceV2: return "wobble_face_v2"
        case .wobbleFaceV3: return "wobble_face_v3"
        case .wobbleFaceV4: return "wobble_face_v4"
        case .wobbleFaceV5: return "wobble_face_v5"
        }
    }
}
